solve avatar
js-tasks-ru/htmlcss-20220317_gleb-sel pull request #12
Opened 2022-04-30 10:49 UTC by blackseliger

2022-04-30 10:50 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-30 12:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-30 13:00 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-01 12:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-01 12:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-01 12:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-05 20:51 UTC, GSemikozov requested changes

2022-05-05 20:51 UTC, GSemikozov commented on assets/css/normalize.css
> -<<<<<<< Updated upstream
конфликт

2022-05-05 20:51 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar-card {
верстаем не карточку аватара с заголовками и пр., а именно аватар - будет всего два хтмл-элемента и классы - .avatar + .avatar__img

2022-05-11 13:08 UTC, blackseliger commented on 06-lection4/01-avatar/avatar.css
> +.avatar-card {
сделал

2022-05-12 14:03 UTC, GSemikozov approved these changes

2022-05-12 14:03 UTC, merged