06 03 srcset
js-tasks-ru/htmlcss-20220317_gleb-sel pull request #15
Opened 2022-05-01 15:23 UTC by blackseliger

Мне кажется как-то не верно решил задание, не уверен в решении.

2022-05-01 15:23 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-01 18:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-01 18:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-01 18:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-05 20:51 UTC, GSemikozov requested changes

2022-05-05 20:51 UTC, GSemikozov commented on assets/css/normalize.css
> -<<<<<<< Updated upstream
не решенный конфликт

2022-05-12 14:02 UTC, GSemikozov requested changes

2022-05-12 14:02 UTC, GSemikozov commented on assets/css/normalize.css
> -<<<<<<< Updated upstream
до сих пор висит

2022-05-12 14:48 UTC, blackseliger commented on assets/css/normalize.css
> -<<<<<<< Updated upstream
гитхаб не показывает ошибки в ПР, в normalize.css тоже сейчас ничего нет, на всякий случай смерджил и запушил  https://github.com/blackseliger/htmlcss-20220317_gleb-sel/blob/b66e54e8571890fea0b5141269ea964037b17f74/assets/css/normalize.css#L343-L350

2022-05-18 18:40 UTC, GSemikozov approved these changes

2022-05-18 18:40 UTC, merged