05 04 page components
js-tasks-ru/htmlcss-20220317_gleb-sel pull request #16
Opened 2022-05-05 17:44 UTC by blackseliger

Мне кажется перемудрил с гридами, многовато их напихал. Но с другой стороны кажется все нормальным. 
Скажите пожалуйста так же, ссылки в блоке aside надо было делать через тег `<a>`? 
Меня так же смутила ссылка Main page которая стоит в фигме особняком ото всех, оставил ее в общем потоке ссылок без доп отступов. 

Мне приходится часто у h1 тегов убирать нативно margin, это правильный подход?
По поводу файловой структуры. Не знаю куда точно кидать css файлы.   Пока создал единую папку в pages 'template' куда закинул все.

2022-05-05 17:45 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-05 20:59 UTC, GSemikozov requested changes

2022-05-05 20:59 UTC, GSemikozov commented on assets/css/normalize.css
> -<<<<<<< Updated upstream
конфликт

2022-05-05 20:59 UTC, GSemikozov commented on pages/template/template.css
> +body {
этот блок и так по умолчанию 100% )

2022-05-05 20:59 UTC, GSemikozov commented on pages/template/template.css
> +.container {
у нас уже есть контейнер, надо подождать пока нужный ПР заедет в мастер

2022-05-05 20:59 UTC, GSemikozov commented on pages/template/template.css
> +.aside__menu {
вынести как отдельный блок

2022-05-05 20:59 UTC, GSemikozov commented on pages/template/template.css
> +.main {
отдельный блок

2022-05-05 20:59 UTC, GSemikozov commented on pages/template/template.css
> +.footer {
футер тоже уже есть, ждем пока подъедет

2022-05-06 06:49 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-06 06:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-06 11:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-06 11:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-06 11:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-06 11:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-06 11:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-06 12:00 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-06 14:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-06 15:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-06 15:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-06 15:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-06 15:22 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-11 13:03 UTC, blackseliger commented on pages/template/template.css
> +.aside__menu {
закинул в отдельную папку весь блок aside

2022-05-11 13:05 UTC, blackseliger commented on pages/template/template.css
> +.main {
main так же закинул в папку main

2022-05-21 15:47 UTC, blackseliger commented on pages/template/template.css
> +.container {
мне пришлось сделать микс, так как страницы компонента есть работа грид дисплея в контейнере. добавил класс page__container. Не уверен, это хороший подход?

2022-05-21 15:50 UTC, blackseliger commented on pages/template/template.css
> +.footer {
С футером тоже пришлось миксовать, добавил page__footer
ниже есть "footer__title page__footer__title"   честно затрудняюсь как правильно надо было назвать  `page__footer__title` ибо если page__title, то это слишком распространенное название. title может быть где угодно (говорю не именно в контексте задачки, а в целом)

2022-05-23 15:13 UTC, GSemikozov requested changes

2022-05-23 15:13 UTC, GSemikozov commented on pages/template/template.css
> +.page__footer__title {
неправильно оформлен класс, не элемент элемента, а просто элемент - .page__footer-title

2022-05-23 15:16 UTC, blackseliger commented on pages/template/template.css
> +.page__footer__title {
поправил, буду знать

2022-05-23 15:28 UTC, GSemikozov approved these changes

2022-05-23 15:28 UTC, merged