add buttons for 03-01-button
js-tasks-ru/htmlcss-20220317_gleb-sel pull request #3
Opened 2022-03-30 21:59 UTC by blackseliger

2022-03-30 22:00 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-31 11:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-03-31 11:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-03-31 15:08 UTC, GSemikozov requested changes

2022-03-31 15:08 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +:root {
глобальные штуки, и вообще любые другие стили которые не относятся в текущему компоненту, здесь оформлять не надо)
для :root уже есть место - в main.css

2022-03-31 15:08 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
ширина не должна быть фиксированной (текст может быть и длиннее 200px)

2022-03-31 15:08 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 15px;
паддинги нужно сразу на .button указать (15px 15px 14px)

2022-03-31 15:08 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_primary-disabled {
вместо отдельного модификатора для disabled, причем отдельно на каждый тип кнопки - надо использовать встроенный псевдо-селектор :disabled (работает "из коробки" и не нужно js-ом навешивать класс чтобы оформить это состояние)

2022-03-31 15:08 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border: none;
чтобы в 2 типах кнопок не дублировать можно указать сразу на .button

2022-03-31 15:08 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_primary-disabled {
кстати, как говорилось, disabled общий для всех и содержит всего 2 свойства: pointer-events: none + opacity: 0.5

2022-03-31 15:08 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    box-sizing: border-box;
сразу задать на .button

2022-03-31 15:08 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    box-sizing: border-box;
и здесь тогда удалить

2022-03-31 15:08 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +            <span class="button__text">Primary</span>
не нужно текст оборачивать в отдельный элемент

2022-04-04 18:32 UTC, GSemikozov requested changes

2022-04-04 18:32 UTC, GSemikozov commented on .gitignore
> +components
удалить (у нас будет много компонентов в этой папке)

2022-04-30 10:40 UTC, GSemikozov approved these changes

2022-04-30 10:40 UTC, merged