add solution for 03-02
js-tasks-ru/htmlcss-20220317_gleb-sel pull request #4
Opened 2022-04-03 12:33 UTC by blackseliger

2022-04-03 12:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-03 12:40 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-03 12:42 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-03 18:57 UTC, GSemikozov requested changes

2022-04-03 18:57 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
ширину не надо фиксировать, иначе сразу минус к возможности переиспользовать

2022-04-03 18:57 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +details[open] .accordion__content {
details[open] .accordion__content -> здесь на элементе должен быть класс, например .accordion__details[open] .accordion__content

2022-04-03 18:57 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +details[open] .accordion__content {
или сразу .accordion__item

2022-04-04 15:00 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-04 15:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-04 18:33 UTC, GSemikozov requested changes

2022-04-04 18:33 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +details > summary {
просто .accordion__summary

2022-04-14 12:03 UTC, GSemikozov requested changes

2022-04-14 12:03 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +details > .accordion__summary {
почему селектор тега + вложенный селектор все еще висит?) нужно оставить .accordion__summary

2022-04-17 17:29 UTC, blackseliger commented on 03-lection1/02-accordion/accordion.css
> +details > .accordion__summary {
неверно понял вас по началу, поправил

2022-04-30 10:41 UTC, GSemikozov requested changes

2022-04-30 10:41 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    background-color: #FFFFFF;
во всех компонентах важно не забывать проставлять цвета из переменных

2022-05-05 20:37 UTC, GSemikozov requested changes

2022-05-05 20:37 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 24px 0 24px 32px;
справа ведь тоже нужен паддинг

2022-05-05 20:37 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 0 49px 8px 0;
а тут получается справа большой отступ а слева 0?

2022-05-11 12:48 UTC, blackseliger commented on 03-lection1/02-accordion/accordion.css
> +    padding: 0 49px 8px 0;
исправил, оставил только нижний отступ 8px

2022-05-12 14:00 UTC, GSemikozov submitted a review, later dismissed

2022-05-12 14:00 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-05-17 19:39 UTC, GSemikozov approved these changes

2022-05-17 19:39 UTC, merged