solve histogram-lection2
js-tasks-ru/htmlcss-20220317_gleb-sel pull request #6
Opened 2022-04-10 14:41 UTC by blackseliger

2022-04-10 14:42 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-10 22:27 UTC, blackseliger commented
Пришлось указать размеры, чтоб компонент не растягивался на всю страницу.

2022-04-14 12:06 UTC, GSemikozov requested changes

2022-04-14 12:06 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +* {margin: 0;}
глобальные сбросы ни в коем случае не описываем внутри компонента

2022-04-14 12:06 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.container {
блок называется .histogram, никаких других блоков в этом файле описывать нельзя)

2022-04-14 12:06 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 354px;
ширину и высоту не фиксируем

2022-04-14 12:06 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 9px;
flex-basis: 9px

2022-04-30 10:42 UTC, GSemikozov requested changes

2022-04-30 10:42 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    border: 1px solid #ACB5BD;
все цвета проставляем из переменных

2022-05-05 20:39 UTC, GSemikozov requested changes

2022-05-05 20:39 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.header__tile {
.histogram__title

2022-05-05 20:39 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    font-weight: 400;
задать здесь общие паддинги, чтобы ниже каждому дочернему элементу не задавать марджины чтобы оттолкнуться от границ блока

2022-05-05 20:39 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +   color: var(--blue);
не хватает стилей оформления текста

2022-05-05 20:39 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                    <div class="histogram__values">
сразу h4

2022-05-12 14:00 UTC, GSemikozov approved these changes

2022-05-12 14:00 UTC, merged